---

- name: Add Packager apt key for PgHero
  apt_key:
    url: https://deb.packager.io/key
  become: yes

- name: Add PgHero apt repository
  apt_repository:
    repo: deb https://deb.packager.io/gh/pghero/pghero xenial master
  become: yes

- name: Update packages
  apt:
    update_cache: yes
  become: yes

- name: Install PgHero
  apt:
    name: pghero
  become: yes
  notify: Restart PgHero

- name: Configure PgHero
  command: 'pghero config:set {{ item }}'
  with_items:
    - 'DATABASE_URL=postgres://{{ pgher_db_username }}:{{ pghero_db_password|urlencode() }}@localhost:5432/{{ postgres_secrets.db_name }}'
    - 'PORT={{ pghero.port }}'
  become: yes
  notify: Restart PgHero
  # TODO: Check the values before setting them, otherwise /etc/pghero/conf.d/other fills up.

- name: Set PgHero to one worker
  command: pghero scale web=1
  become: yes
  notify: Restart PgHero

- name: Ensure PgHero is started
  service:
    name: pghero
    state: started
  become: yes

- include: nginx.yml
