---

- name: Add Packager apt key for PgHero
  apt_key:
    keyserver: https://deb.packager.io/key
  become: yes

- name: Add PgHero apt repository
  apt_repository:
    repo: deb https://deb.packager.io/gh/pghero/pghero xenial master
  become: yes

- name: Update packages
  apt:
    update_cache: yes
  become: yes

- name: Install PgHero
  apt:
    name: pghero
  become: yes

- name: Configure PgHero
  command: 'pghero config:set {{ item }}'
  with_items:
    - 'DATABASE_URL=postgres://{{ postgres_secrets.username }}:{{ postgres_secrets.password }}@localhost:5432/{{ postgres_secrets.db_name }}'
    - 'PGHERO_USERNAME={{ pghero_secrets.username }}'
    - 'PGHERO_PASSWORD={{ pghero_secrets.password }}'
    - 'PORT={{ pghero.port }}'
  become: yes

- include: nginx.yml
