---

- name: Install Tarsnapper
  pip:
    name: tarsnapper
    executable: pip3
    state: latest
  become: yes

- name: Create Tarsnapper directory
  file:
    path: '{{ tarsnapper_dir }}'
    state: directory
  become: yes

- name: Place Tarsnapper configuration
  template:
    src: tarsnapper.conf.j2
    dest: '{{ tarsnapper_dir }}/tarsnapper.conf'
  become: yes

- name: Place Tarsnap configuration
  template:
    src: tarsnap.conf.j2
    dest: '{{ tarsnap_conf_path }}'
  become: yes

- name: Run Tarsnapper on cron
  cron:
    name: "Tarsnapper backups"
    minute: 0
    hour: '*/4'
    user: root
    job: 'PATH=$PATH:/usr/local/bin tarsnapper -c {{ tarsnapper_dir }}/tarsnapper.conf make'
    cron_file: tarsnapper_backups
  become: yes

# Be sure to run:
# sudo tarsnap-keygen --keyfile /root/tarsnap.key --user email.address --machine mymachine
