---

galaxy_info:
  author: EDITD devs
  description: A role for creating supervisor tasks
  company: EDITD
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  categories:
  - cloud
  - development
  - packaging
  - system
  - web
dependencies: []
