---

- name: Install byobu
  apt:
    name: byobu
  become: yes

- name: Make byobu the default
  command: byobu-enable

- name: Enable colorful byobu prompt
  command: byobu-enable-prompt

- name: Add tmux config
  template:
    src: tmux.conf.j2
    dest: '{{ ansible_env.HOME }}/.byobu/.tmux.conf'
