---

- name: Install aptitude for certain apt module commands
  apt:
    name: aptitude
  become: yes

- name: Update apt and upgrade packages
  apt:
    update_cache: yes
    upgrade: safe
  become: yes

- name: Install common default software
  apt:
    name: "{{ item }}"
  with_items:
    - build-essential
    - htop
    - libffi-dev
    - libpcre3
    - libpcre3-dev
    - libpq-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - ntp
    - python-dev
    - python-pip
    - python-psycopg2
    - python-setuptools
    - silversearcher-ag
    - zlib1g-dev
  become: yes

- name: Install common system Python packages
  pip:
    name: '{{ item }}'
  with_items:
    - virtualenv
  become: yes

- name: Configure Supervisor
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/supervisor.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Reload Supervisor configuration

- include: byobu.yml

# Security.
- include: allow_only_ssh_login.yml
- include: ufw.yml
- include: fail2ban.yml
