---

# No bionic available yet...
#- name: Add pypa apt repository for pipenv
#  apt_repository:
#      repo: ppa:pypa/ppa
#  become: yes
#
#- name: Install pipenv
#  apt:
#    name:
#      - software-properties-common
#      - python-software-properties
#      - pipenv
#    state: latest
#  become: yes

- name: Install pipenv
  pip:
    name: pipenv
    executable: /home/ubuntu/.local/bin/pip3
    state: latest
  become: yes
