version: 2

jobs:
  build:
    working_directory: ~/manabi
    docker:
      - image: circleci/python:3.6.5-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:10.3-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
      - image: redis:4.0.9
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          # Default branch if not
          - v1-dep-master-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo apt-get install mecab libmecab-dev mecab-ipadic mecab-ipadic-utf8
            sudo pip install pipenv
            pipenv install --deploy
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy:
    working_directory: ~/manabi
    docker:
      - image: circleci/python:2.7.14
    environment:
        PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
          # This branch if available
          - v1-deploy-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          # Default branch if not
          - v1-deploy-dep-master-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            sudo apt-get install python-dev
            sudo pip install pipenv
            cd config
            ssh-keyscan vps98220.vps.ovh.ca >> ~/.ssh/known_hosts
            echo $ANSIBLE_VAULT_PASSWORD > ~/.vault_password.txt && ./deploy.sh --vault-password-file=~/.vault_password.txt || ( rm ~/.vault_password.txt && exit 1 )
            rm ~/.vault_password.txt
            curl https://manabi.io
      - save_cache:
          key: v1-deploy-dep-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
