---

dependencies:
  - role: ansible-supervisor_task
    name: carbon-cache
    command: "carbon-cache --config='{{ carbon.config_path }}' --pidfile /var/run/carbon-cache.pid --nodaemon start"
    user: '{{ carbon.user }}'
    numprocs: 1

  - role: ansible-supervisor_task
    name: graphite-api
    command: 'uwsgi --socket="{{ graphite_api.uwsgi_socket }}" --chmod-socket=666 -w graphite_api.app:app --processes=2 --enable-threads --max-requests=10000 --vacuum'
    process_name: uwsgi
    user: ubuntu
    tags: uwsgi
    numprocs: 1

  - role: ansible-supervisor_task
    name: grafana
    command: "grafana-server --config='{{ grafana.config_path }}' cfg:default.paths.data='{{ grafana.data_dir }}' cfg:default.paths.plugins='{{ grafana.plugins_dir }}'"
    user: '{{ grafana.user }}'
    directory: '{{ grafana.home_dir }}'
    numprocs: 1

  - role: oauth2_proxy
    oauth2_proxy_app_name: grafana
    oauth2_proxy_client_id: '{{ grafana_secrets.github_client_id }}'
    oauth2_proxy_client_secret: '{{ grafana_secrets.github_client_secret }}'
    oauth2_proxy_port: '{{ grafana.oauth2_proxy_port }}'
    oauth2_proxy_upstream: 'http://localhost:{{ grafana.port }}'
    oauth2_proxy_redirect_url: 'https://{{ grafana.hostname }}/oauth2/callback'
    oauth2_proxy_cookie_domain: '{{ grafana.hostname }}'
