---

dependencies:
  - { role: common, tags: ['common'] }
  - { role: uwsgi, tags: ['uwsgi'] }
  - { role: nginx, tags: ['nginx'] }
  - { role: postgresql, tags: ['postgresql'] }
  - { role: redis, tags: ['redis'] }
  - { role: memcached, tags: ['memcached'] }
