---

postgres_exporter:
  port: 9187

carbon:
  user: _graphite
  group: _graphite
  config_path: /etc/carbon/carbon.conf
  line_receiver_port: 8380
  udp_receiver_port: 8380
  pickle_receiver_port: 8381

graphite_api:
  uwsgi_socket: /tmp/graphite_api_uwsgi.socket
  config_path: /etc/graphite-api.yaml
  port: 8280

grafana:
  user: grafana
  group: grafana
  home_dir: /usr/share/grafana
  data_dir: /var/lib/grafana
  plugins_dir: /var/lib/grafana/plugins
  config_path: /etc/grafana/grafana.ini
  port: 8180
  oauth2_proxy_port: 8181
  hostname: grafana.manabi.io
