---

- name: Machine-level configuration directory for Manabi
  file:
    path: /etc/manabi
    state: directory
    owner: ubuntu
    group: ubuntu
  become: yes

- name: Mark machine as production
  file:
    path: /etc/manabi/production
    state: touch
    owner: ubuntu
    group: ubuntu
  become: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers

- name: Pull source
  git:
    repo: git@github.com:aehlke/manabi.git
    dest: '{{ app_root_path }}'
    version: master
    accept_hostkey: yes
    force: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers
  tags: git-pull

- name: Install python dependencies
  pip:
    requirements: '{{ app_root_path }}/requirements.txt'
    virtualenv: '{{ app_virtualenv_path }}'
    virtualenv_python: python2.7
    virtualenv_site_packages: no
  notify:
    - Reload uwsgi
    - Restart RQ workers

- name: Place decrypted production secrets
  copy:
    src: vault/settings_production_secrets.py
    dest: '{{ app_root_path }}/manabi/settings_production_secrets.py'
    force: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers
