---

- import_tasks: mecab.yml

- name: Machine-level configuration directory for Manabi
  file:
    path: /etc/manabi
    state: directory
    owner: ubuntu
    group: ubuntu
  become: yes

- name: Mark machine as production
  file:
    path: /etc/manabi/production
    state: touch
    owner: ubuntu
    group: ubuntu
  become: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers

- name: Pull source
  git:
    repo: git@github.com:aehlke/manabi.git
    dest: '{{ app_root_path }}'
    version: master
    depth: 1
    accept_hostkey: yes
    force: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers
  tags: git-pull

- name: Clean pyc files
  shell: bash -lc "pipenv run python manage.py clean_pyc --path {{ app_root_path }}"
  args:
    chdir: '{{ app_root_path }}'

- name: Install python dependencies
  shell: bash -lc "pipenv install --deploy"
  args:
    chdir: '{{ app_root_path }}'
  notify:
    - Reload uwsgi
    - Restart RQ workers

- name: Place decrypted production secrets
  copy:
    src: vault/settings_production_secrets.py
    dest: '{{ app_root_path }}/manabi/settings_production_secrets.py'
    force: yes
  notify:
    - Reload uwsgi
    - Restart RQ workers

- name: Migrate database
  shell: bash -lc "pipenv run python manage.py migrate --noinput"
  args:
    chdir: '{{ app_root_path }}'

- include: webpack.yml

- name: Add ubuntu to www-data group to be able to manipulate static files
  user:
    name: ubuntu
    groups: www-data
    append: yes
  become: yes

- name: Add www-data to ubuntu group to be able to read uploaded media
  user:
    name: www-data
    groups: ubuntu
    append: yes
  become: yes

- name: Collect static files
  shell: 'bash -lc "pipenv run python manage.py collectstatic --noinput {{ manabi_collectstatic_extra_args }}"'
  args:
    chdir: '{{ app_root_path }}'
  tags: collectstatic

- name: Assign ownership of static files to www-data
  file:
    path: '{{ app_static_files_path }}'
    state: directory
    mode: 'u=rwx,g=rwx'
    owner: www-data
    group: www-data
    recurse: yes
  become: yes

- import_tasks: reader_feeds.yml
