---

- name: Checkout source
  git:
    repo: git@github.com:aehlke/manabi.git
    dest: '{{ app_root_path }}'
    version: master
    accept_hostkey: yes
    force: yes
  notify: Reload uwsgi

- name: Install python dependencies
  pip:
    requirements: '{{ app_root_path }}/requirements.txt'
    virtualenv: '{{ app_virtualenv_path }}'
    virtualenv_python: python2.7
    virtualenv_site_packages: no
  notify: Reload uwsgi

- name: Place decrypted production secrets
  copy:
    src: vault/settings_production_secrets.py
    dest: '{{ app_root_path }}/manabi/settings_production_secrets.py'
    force: yes
  notify: Reload uwsgi
