---

- name: Generate Manabi Reader RSS feeds on cron
  cron:
    name: "Generate feed {{ item }}"
    minute: 10
    hour: '*/8'
    user: ubuntu
    job: 'PATH=$PATH:/usr/local/bin bash -lc "cd {{ app_root_path }} && cron-sentry --report-all pipenv run python manage.py {{ item }}" >> /var/log/manabi_reader_feeds 2&>1'
    cron_file: manabi_reader_feeds
  with_items:
      - generate_nhk_easy_news_feed
