---

- name: Install node and npm
  apt:
    name: '{{ item }}'
  with_items:
    - nodejs
    - npm
  become: yes

- name: Install npm dependencies
  npm:
    path: '{{ app_root_path }}'

- name: Build with webpack
  command: './node_modules/.bin/webpack --config webpack_production.config.js'
  args:
    chdir: '{{ app_root_path }}'
