---

# https://askubuntu.com/questions/1088662/npm-depends-node-gyp-0-10-9-but-it-is-not-going-to-be-installed
- name: Install node and npm
  apt:
    name:
      - nodejs-dev
      - node-gyp
      - libssl1.0-dev
      - nodejs
      - npm
  become: yes

- name: Install npm dependencies
  npm:
    path: '{{ app_root_path }}'

- name: Build with webpack
  command: './node_modules/.bin/webpack --config webpack_production.config.js'
  args:
    chdir: '{{ app_root_path }}'
