# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 03:14


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=700, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('thumbnail_url', models.URLField(max_length=700)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
