# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-31 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_sources', '0002_readersource_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readersource',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
