---

dependencies:
  - { role: redis, tags: ['redis'] }

  - role: ansible-supervisor_task
    name: rq
    command: '{{ app_virtualenv_path }}/bin/python {{ app_root_path }}/manage.py rqworker --worker-class "manabi.rq_worker.ManabiWorker"'
    directory: '{{ app_root_path }}'
    # RQ requires the TERM signal to perform a warm shutdown. If RQ does not die
    # within 10 seconds, supervisor will forcefully kill it
    stopsignal: TERM
    process_name: rq
    user: ubuntu
    numprocs: 1

  - role: oauth2_proxy
    oauth2_proxy_app_name: rq_dashboard
    oauth2_proxy_client_id: '{{ rq_dashboard_secrets.github_client_id }}'
    oauth2_proxy_client_secret: '{{ rq_dashboard_secrets.github_client_secret }}'
    oauth2_proxy_port: '{{ rq_dashboard.oauth2_proxy_port }}'
    oauth2_proxy_upstream: 'http://127.0.0.1:{{ rq_dashboard.port }}'
    oauth2_proxy_redirect_url: 'https://{{ rq_dashboard.hostname }}/oauth2/callback'

  - role: ansible-supervisor_task
    name: rq-dashboard
    command: '{{ app_virtualenv_path }}/bin/rq-dashboard --bind 127.0.0.1 --port {{ rq_dashboard.port }} --redis-host 127.0.0.1 --redis-port 6379 --redis-database 9 --interval 1000'
    directory: '{{ app_root_path }}'
    # RQ requires the TERM signal to perform a warm shutdown. If RQ does not die
    # within 10 seconds, supervisor will forcefully kill it
    stopsignal: TERM
    process_name: rq-dashboard
    user: ubuntu
    numprocs: 1
