---

dependencies:
  - { role: redis, tags: ['redis'] }
  - role: ansible-supervisor_task
    name: rq
    command: '{{ app_virtualenv_path }}/bin/python {{ app_root_path }}/manage.py rqworker default --worker-class "manabi.rq_worker.ManabiWorker"'
    directory: '{{ app_root_path }}'
    # RQ requires the TERM signal to perform a warm shutdown. If RQ does not die
    # within 10 seconds, supervisor will forcefully kill it
    stopsignal: TERM
    process_name: rq
    user: ubuntu
    numprocs: 1
  - role: ansible-supervisor_task
    name: rq-dashboard
    command: '{{ app_virtualenv_path }}/bin/rq-dashboard --bind 127.0.0.1 --port {{ rq.port }} --redis-host 127.0.0.1 --redis-port 6379 --redis-database 9 --interval 1000'
    directory: '{{ app_root_path }}'
    # RQ requires the TERM signal to perform a warm shutdown. If RQ does not die
    # within 10 seconds, supervisor will forcefully kill it
    stopsignal: TERM
    process_name: rq-dashboard
    user: ubuntu
    numprocs: 1
