# Generated by Django 2.0.4 on 2018-07-19 01:31

from django.db import migrations, models


def forwards(apps, schema_editor):
    from django.conf import settings
    import itunesiap

    Subscription = apps.get_model('subscriptions', 'Subscription')

    for subscription in Subscription.objects.all():
        itunes_receipt = subscription.latest_itunes_receipt
        response = itunesiap.verify(
            itunes_receipt,
            password=settings.ITUNES_SHARED_SECRET,
            env=itunesiap.env.review)
        latest_receipt_info = response.latest_receipt_info[-1]

        subscription.original_transaction_id = (
            latest_receipt_info['original_transaction_id'])
        subscription.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_inapppurchaselogitem_subscriptionupdatenotificationlogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='original_transaction_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RunPython(forwards),
    ]
