# Generated by Django 2.0.4 on 2018-07-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_subscription_original_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='original_transaction_id',
            field=models.CharField(max_length=300),
        ),
    ]
