# Generated by Django 2.0.4 on 2018-07-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20180719_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_trial_period',
            field=models.BooleanField(default=False),
        ),
    ]
