# Generated by Django 2.1.1 on 2018-09-29 01:34

from django.db import migrations


def forwards(apps, schema_editor):
    from manabi.apps.subscriptions.models import InAppPurchaseLogItem

    Subscription = apps.get_model('subscriptions', 'Subscription')

    for log_item in InAppPurchaseLogItem.objects.filter(
        original_transaction_id__isnull=True,
    ):
        subscription = Subscription.objects.get(subscriber=log_item.subscriber)
        subscription.original_transaction_id = log_item.original_transaction_id
        subscription.save(update_fields=['original_transaction_id'])

        # Reapply transaction to update subscription expires_date
        log_item.process_itunes_receipt()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20180719_1930'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
