# Generated by Django 2.1.5 on 2019-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_fix_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionupdatenotificationlogitem',
            name='notification_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subscriptionupdatenotificationlogitem',
            name='production_environment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_trial_period',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sandbox',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
