# Generated by Django 2.0 on 2019-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_auto_20190228_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
