# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 03:08


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_remove_card_leech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='picture',
        ),
    ]
