# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-03 03:57


import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0025_fix_ruby_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='placeholder', editable=False, populate_from=b'name'),
            preserve_default=False,
        ),
    ]
