# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-03 03:57
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Deck = apps.get_model('flashcards', 'Deck')

    for deck in Deck.objects.all().iterator():
        deck.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0026_add_deck_slug'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
