# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-03 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0027_prefill_deck_slug'),
    ]

    operations = [
    ]
