# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-03 17:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0029_non_unique_slugs'),
    ]

    operations = [
    ]
