# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-03 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0030_prefill_deck_slug_redux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='slug',
        ),
    ]
