# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-23 03:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0040_auto_20170123_0314'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([('owner', 'active', 'suspended', 'due_at')]),
        ),
    ]
