# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-06 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0043_sync_deck_images_and_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='randomize_card_order',
            field=models.BooleanField(default=True),
        ),
    ]
