# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-10 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0045_manabi_4k_deck_creation_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='priority',
        ),
    ]
