# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-11 02:31


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0047_deck_collection_ordinal'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='cardhistory',
            index_together=set([('card', 'was_new', 'reviewed_at')]),
        ),
    ]
