# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-18 20:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0048_auto_20170211_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deck_suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
