# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    Deck = apps.get_model('flashcards', 'Deck')
    Card = apps.get_model('flashcards', 'Card')

    for deck in Deck.objects.all():
        deck.card_count = Card.objects.filter(deck=deck).filter(active=True, suspended=False).count()
        deck.save(update_fields=['card_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0051_auto_20170218_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='card_count',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(forwards)
    ]
