# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 03:07


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0052_deck_card_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardhistory',
            name='interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='card_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([('owner', 'due_at', 'active', 'suspended', 'due_at', 'fact'), ('deck', 'owner'), ('owner', 'due_at', 'active', 'suspended')]),
        ),
    ]
