# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 06:38


from django.db import migrations


def forwards(apps, schema_editor):
    from manabi.apps.flashcards.models import Deck

    for deck in Deck.objects.all().iterator():
        deck.refresh_card_count()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0054_auto_20171211_0313'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
