# Generated by Django 2.1.3 on 2018-11-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0057_auto_20180721_0221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set(),
        ),
        migrations.RunSQL(
            '''
            ALTER TABLE flashcards_deck
                ADD CONSTRAINT flashcards_deck_unique_name_for_owner_if_active EXCLUDE (owner_id WITH =, name WITH =, synchronized_with_id WITH =) WHERE (active IS TRUE);
            '''
        ),
    ]
