# Generated by Django 2.1.3 on 2019-01-08 01:46

from django.db import migrations


def forwards(apps, schema_editor):
    from manabi.apps.flashcards.models import Deck

    for deck in Deck.objects.filter(
        synchronized_with__isnull=False,
    ).iterator():
        deck.refresh_card_count()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0058_unique_only_required_for_active_decks'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
