# Generated by Django 2.1.5 on 2019-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0059_refresh_card_counts_after_subscribe_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='jmdict_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='active',
            field=models.BooleanField(blank=True, db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='randomize_card_order',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='shared',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='fact',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='fact',
            name='forked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
