# Generated by Django 2.1.5 on 2019-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0060_auto_20190120_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='jmdict_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
