# Generated by Django 2.2.5 on 2019-11-03 04:00

from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    from manabi.apps.flashcards.models import Fact, Deck

    for fact in Fact.objects.iterator():
        card_attrs = {
            'fact_suspended': fact.suspended,
            'deck_suspended': fact.deck.suspended,
        }
        if not fact.active:
            card_attrs['active'] = False
        fact.card_set.update(**card_attrs)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0062_auto_20190120_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fact_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together={('deck', 'owner'), ('owner', 'due_at', 'active', 'suspended'), ('owner', 'due_at', 'active', 'suspended', 'due_at', 'fact', 'deck_suspended', 'fact_suspended')},
        ),
        migrations.RunPython(forwards),
    ]
