---

- name: Restart sshd
  service:
    name: sshd
    state: restarted
  become: yes

- name: Restart ufw
  service:
    name: ufw
    state: restarted
  become: yes

- name: Reload Superivsor configuration
  shell: supervisorctl reread && supervisorctl update
  become: yes
