- name: Install dependencies
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - supervisor
  sudo: yes

- name: Installing task {{ name }}
  template: src=task.conf.j2 dest={{ supervisor_config_dir }}/{{ name }}.conf
  sudo: yes
  when: '{{ state == "present" }}'

- name: Removing task {{ name }}
  file: path={{ supervisor_config_dir }}/{{ name }}.conf state=absent
  sudo: yes
  when: '{{ state == "absent" }}'

- name: Ensure supervisord is started
  service: name=supervisor state=started enabled=yes
  sudo: yes

- name: Update supervisor
  command: "{{ supervisorctl_command }} update"
  sudo: yes

- name: Restart task {{ name }}
  command: "{{ supervisorctl_command }} restart {{ name }}:*"
  when: '{{ restart_task and state == "present" }}'
  sudo: yes

- name: Send restart signal to task {{ name }}
  shell: "kill -s {{ restart_signal }} `cat {{ restart_pidfile }}`"
  when: '{{ restart_signal and restart_pidfile and state == "present" }}'
  sudo: yes
