# global/supervisord config

supervisor_config_dir: "/etc/supervisor/conf.d/"
supervisorctl_command: "supervisorctl"

restart_task: yes
restart_signal: null
restart_pidfile: null


# supervisor tasks config

redirect_stderr: "false"
autorestart: "true"
autostart: "true"
env_vars: {}
numprocs: 1
process_name: "%(program_name)s_%(process_num)02d"
state: "present"
