---

- name: Install uwsgi
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
  become: yes

- name: Install uwsgi utilities
  pip:
    name:
      - uwsgitop
    state: latest
  become: true
