---

- name: Install uwsgi
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
  become: yes

- name: Install uwsgi utilities
  pip:
    name: uwsgitop
    executable: /home/ubuntu/.local/bin/pip3
    state: latest
  become: true
