---

- name: Install uwsgi
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
  become: yes

- name: Install uwsgi utilities
  pip:
    name: uwsgitop
    executable: python3.7 -m pip
    state: latest
  become: true
