# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-01 00:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featured_decks', '0002_auto_20170131_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureddeck',
            name='deck',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.Deck'),
        ),
    ]
