---

- name: Install collectd and related packages
  apt:
    name: '{{ item }}'
      - collectd
      - collectd-utils
  become: yes
  tags: collectd

- name: Configure Carbon
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    mode: 0644
  become: yes
  notify: Restart collectd
  tags: collectd

- name: Ensure collectd daemon is running
  service:
    name: collectd
    state: started
  become: yes
  tags: collectd
