---

- name: Install collectd and related packages
  apt:
    name: '{{ item }}'
  become: yes
  with_items:
    - collectd
    - collectd-utils

- name: Configure Carbon
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    mode: 0644
  become: yes
  notify: Restart collectd

- name: Ensure collectd daemon is running
  service:
    name: collectd
    state: started
  become: yes
