---

- name: Import Grafana apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key
  become: yes

- name: Add Grafana repository
  apt_repository:
    repo: "https://packages.grafana.com/oss/deb stable main"
    update_cache: yes
  become: yes

- name: Install Grafana
  apt:
    pkg: grafana
  become: yes
  notify: Restart Grafana

- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: '{{ grafana.user }}'
    group: '{{ grafana.group }}'
    mode: 0644
  become: yes
  notify: Restart Grafana

- name: Add Grafana nginx site
  template:
    src: nginx-grafana.conf.j2
    dest: /etc/nginx/sites-enabled/grafana.conf
  become: yes
  notify: Reload nginx
