---

- name: Install Graphite and related packages
  apt:
    name: '{{ item }}'
  become: yes
  with_items:
    - build-essential
    - graphite-carbon
    - libpq-dev

- name: Install Graphite-API
  pip:
    name: '{{ item }}'
  become: yes
  with_items:
    - graphite-api
    - graphite-api[sentry]

- name: Configure Graphite-API
  template:
    src: graphite-api.yaml.j2
    dest: /etc/graphite-api.yaml
    mode: 0644
  become: yes
  notify: Restart Graphite-API

- name: Add Graphite-API nginx site
  template:
    src: nginx-graphite-api.conf.j2
    dest: /etc/nginx/sites-enabled/graphite-api.conf
  become: yes
  notify: Reload nginx
