---

- name: Add Prometheus nginx site
  template:
    src: nginx-prometheus.conf.j2
    dest: /etc/nginx/sites-enabled/prometheus.conf
  become: yes
  notify: Reload nginx

- name: Install Docker for postgres_exporter
  apt:
    name: docker
  become: yes
