---

dependencies:
  - role: ansible-supervisor_task
    name: uwsgi
    directory: {{ app_root_path }}
    command: 'uwsgi --socket "{{ uwsgi_socket }}" -H "{{ app_virtualenv_path }}" --module manabi.wsgi --processes 3 --stats /tmp/manabi_uwsgi_stats.socket --vacuum'
    process_name: uwsgi
    user: ubuntu
    tags: uwsgi
    numprocs: 1
