---

dependencies:
  - role: ansible-supervisor_task
    name: uwsgi
    directory: '{{ app_root_path }}'
    command: "bash -lc \"uwsgi --socket='{{ uwsgi_socket }}' --chmod-socket=666 --virtualenv='`pipenv --venv`' -w manabi.wsgi:application --processes=3 --ignore-sigpipe --die-on-term --enable-threads --max-requests=10000 --stats=/tmp/manabi_uwsgi_stats.socket --vacuum\""
    env_vars:
      PRODUCTION: 1
    process_name: uwsgi
    user: ubuntu
    tags: uwsgi
    numprocs: 1
