---

dependencies:
  - role: ansible-supervisor_task
    task_name: uwsgi
    directory: '{{ app_root_path }}'
    command: "bash -lc 'uwsgi --plugin python37 --socket=\"{{ uwsgi_socket }}\" --chmod-socket=666 --virtualenv=\"$(pipenv --venv)\" -w manabi.wsgi:application --processes=4 --ignore-sigpipe --die-on-term --enable-threads --max-requests=10000 --stats=/tmp/manabi_uwsgi_stats.socket --vacuum'"
    env_vars:
      PRODUCTION: 1
    process_name: uwsgi
    user: ubuntu
    tags: uwsgi
    numprocs: 1
