---

- hosts: production
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
    - name: Ensure Python 3 is installed
      raw: sudo bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qy python3-minimal)"
      become: true

- hosts: production
  remote_user: ubuntu
  roles:
    - { role: manabi, tags: ['manabi'] }
    # FIXME: Currently broken in Bionic: - { role: pghero, tags: ['pghero'] }
    - { role: stats, tags: ['stats'] }
    - { role: tarsnapper, tags: ['tarsnap'] }
