---

- name: Install nginx
  apt:
    name: nginx-full
  become: yes

- name: Disable Ubuntu's own automatic startup of nginx since we use Supervisor
  command: 'update-rc.d -f nginx disable'
  become: yes

- name: Allow nginx to write to logs
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755
  become: yes

- name: Create files directories for nginx
  file:
    path: '{{ item }}'
    state: directory
    mode: 'u=rwx,g=rwx'
    owner: www-data
    group: www-data
    recurse: yes
  become: yes
  with_items:
    - '{{ app_static_files_path }}'
    - '{{ app_media_path }}'

- name: Disable default nginx welcome server
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/sites-enabled/default
  become: yes
  notify: Reload nginx

- name: Add nginx sites
  template:
    src: templates/manabi.conf.j2
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
  with_items:
    - nginx
    - manabi
    - manabi-reader
    - discourse
  become: yes
  notify: Reload nginx
