---

- name: Download binary
  unarchive:
    src: https://github.com/bitly/oauth2_proxy/releases/download/v2.1/oauth2_proxy-2.1.linux-amd64.go1.6.tar.gz
    remote_src: yes
    dest: /usr/local/bin/oauth2_proxy
    mode: u=rwx,g=rx,o=r
    owner: ubuntu
    group: ubuntu
  become: yes
