---

- name: Stop Discourse
  command: ./launcher stop app
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: yes

- name: Start Discourse
  command: ./launcher start app --docker-args --net=host --skip-mac-address
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: yes

- name: Restart Discourse
  command: ./launcher restart app --docker-args --net=host --skip-mac-address
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: yes

- name: Rebuild Discourse
  command: ./launcher rebuild app --docker-args --net=host --skip-mac-address
  args:
    chdir: "{{ discourse_location }}"
  ignore_errors: yes
  become: yes

- name: Bootstrap Discourse
  command: ./launcher bootstrap app --docker-args --net=host --skip-mac-address
  args:
    chdir: "{{ discourse_location }}"
  become: yes
